### ISSUE TITLE
Python Assignee Table Script Fails with data type error

### ISSUE THREAD

**Issue by sarvothaman** [CSSIP-AIR/PatentsView-Code-Snippets#2]
When running the assignee python script with data file downloaded from data.patentsview.org/20200331/download/assignee.tsv.zip it fails with the following message:

```
sys:1: DtypeWarning: Columns (2,3) have mixed types.Specify dtype option on import or set low_memory=False.
488264
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 488264 entries, 0 to 488263
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            488264 non-null  object
 1   type          488264 non-null  int64
 2   name_first    48561 non-null   object
 3   name_last     48561 non-null   object
 4   organization  439703 non-null  object
dtypes: int64(1), object(4)
memory usage: 18.6+ MB
Traceback (most recent call last):
  File "assignee.py", line 25, in <module>
    print(df.describe(df.select_dtypes(include='int')))
  File "/home/smadhavan/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 9847, in describe
    validate_percentile(percentiles)
  File "/home/smadhavan/.local/lib/python3.6/site-packages/pandas/util/_validators.py", line 376, in validate_percentile
    if not all(0 <= qs <= 1 for qs in q_arr):
  File "/home/smadhavan/.local/lib/python3.6/site-packages/pandas/util/_validators.py", line 376, in <genexpr>
    if not all(0 <= qs <= 1 for qs in q_arr):
TypeError: '<=' not supported between instances of 'int' and 'numpy.str_'
```

**Comment by ckjohnson7** [comment]
resolved type error issue
