### ISSUE TITLE
Python Figures Script fails with data type error

### ISSUE THREAD

**Issue by sarvothaman** [CSSIP-AIR/PatentsView-Code-Snippets#4]
The script for figures fails with following message
```
                        uuid patent_id  num_figures  num_sheets
0  00000elf8qlpdyy2gtsbfucud   7133077           20          20
1  00006yl1s7uqdhcy99jepbywa   6682704           21          12
2  00007dvtzhycmwsu8x1ykbhkz   7327967           12          10
3  0000i4id1c4mm8p4ka4hegxj9   7604847            2           1
4  0001g75b1ei2d0tr7y12j7u7i   6111098            4           2
6808932
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6808932 entries, 0 to 6808931
Data columns (total 4 columns):
 #   Column       Dtype
---  ------       -----
 0   uuid         object
 1   patent_id    object
 2   num_figures  int64
 3   num_sheets   int64
dtypes: int64(2), object(2)
memory usage: 207.8+ MB
Traceback (most recent call last):
  File "figures.py", line 22, in <module>
    print(df.describe(df.select_dtypes(include='int')))
  File "/home/smadhavan/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 9847, in describe
    validate_percentile(percentiles)
  File "/home/smadhavan/.local/lib/python3.6/site-packages/pandas/util/_validators.py", line 376, in validate_percentile
    if not all(0 <= qs <= 1 for qs in q_arr):
  File "/home/smadhavan/.local/lib/python3.6/site-packages/pandas/util/_validators.py", line 376, in <genexpr>
    if not all(0 <= qs <= 1 for qs in q_arr):
TypeError: '<=' not supported between instances of 'int' and 'numpy.str_'
```

**Comment by ahasanbasri** [comment]
Last line of code has been changed to **print(df.describe(include='float64'))**
