### ISSUE TITLE
Python Script for NBER, NBER Category  & NBER Subcategory fails with data type error

### ISSUE THREAD

**Issue by sarvothaman** [CSSIP-AIR/PatentsView-Code-Snippets#6]
The error message:
```
5105937
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5105937 entries, 0 to 5105936
Data columns (total 4 columns):
 #   Column          Dtype
---  ------          -----
 0   uuid            object
 1   patent_id       object
 2   category_id     int64
 3   subcategory_id  int64
dtypes: int64(2), object(2)
memory usage: 155.8+ MB
Traceback (most recent call last):
  File "nber.py", line 25, in <module>
    print(df.describe(df.select_dtypes(include='int')))
  File "/home/smadhavan/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 9847, in describe
    validate_percentile(percentiles)
  File "/home/smadhavan/.local/lib/python3.6/site-packages/pandas/util/_validators.py", line 376, in validate_percentile
    if not all(0 <= qs <= 1 for qs in q_arr):
  File "/home/smadhavan/.local/lib/python3.6/site-packages/pandas/util/_validators.py", line 376, in <genexpr>
    if not all(0 <= qs <= 1 for qs in q_arr):
TypeError: '<=' not supported between instances of 'int' and 'numpy.str_'
```

**Comment by ckjohnson7** [comment]
resolved type error issue
