### ISSUE TITLE
Python Non Inventor Applicant Script Fails with data type error

### ISSUE THREAD

**Issue by sarvothaman** [CSSIP-AIR/PatentsView-Code-Snippets#7]
```
4123668
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4123668 entries, 0 to 4123667
Data columns (total 9 columns):
 #   Column          Dtype
---  ------          -----
 0   uuid            object
 1   patent_id       object
 2   rawlocation_id  object
 3   lname           object
 4   fname           object
 5   organization    object
 6   sequence        int64
 7   designation     object
 8   applicant_type  object
dtypes: int64(1), object(8)
memory usage: 283.1+ MB
Traceback (most recent call last):
  File "non_inventor_applicant.py", line 25, in <module>
    print(df.describe(df.select_dtypes(include='int')))
  File "/home/smadhavan/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 9847, in describe
    validate_percentile(percentiles)
  File "/home/smadhavan/.local/lib/python3.6/site-packages/pandas/util/_validators.py", line 376, in validate_percentile
    if not all(0 <= qs <= 1 for qs in q_arr):
  File "/home/smadhavan/.local/lib/python3.6/site-packages/pandas/util/_validators.py", line 376, in <genexpr>
    if not all(0 <= qs <= 1 for qs in q_arr):
TypeError: '<=' not supported between instances of 'int' and 'numpy.str_'
```

**Comment by ckjohnson7** [comment]
resolved type error issue
